---
- name: Phase 1 - Prepare All Nodes
  hosts: k8s_cluster
  become: true
  roles:
    - common

- name: Phase 2 - Setup Control Plane
  hosts: master
  become: true
  roles:
    - k3s_master

- name: Phase 3 - Setup Workers & Labeling
  hosts: workers
  become: true
  roles:
    - k3s_worker

- name: Phase 4 - Deploy Observability Workloads
  hosts: master
  become: true
  roles:
    - observability

- name: Phase 5 - Deploy Forgejo
  hosts: master
  become: true
  roles:
    - forgejo