apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wekan.fullname" . }}
  labels:
    {{- include "wekan.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wekan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wekan.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: wekan
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: {{ .Values.existingSecret.mongoUrlKey }}
            - name: ROOT_URL
              value: {{ .Values.env.rootUrl | quote }}
            - name: PORT
              value: {{ .Values.env.port | quote }}
            - name: WITH_API
              value: {{ .Values.env.withApi | quote }}
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
