apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wekan.fullname" . }}
  labels:
    {{- include "wekan.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "wekan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wekan.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: wekan
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: {{ .Values.existingSecret.mongoUrlKey }}
            - name: ROOT_URL
              value: {{ .Values.env.rootUrl | quote }}
            - name: PORT
              value: {{ .Values.env.port | quote }}
            - name: WITH_API
              value: {{ .Values.env.withApi | quote }}
            - name: MAIL_URL
              value: {{ .Values.env.mailUrl | quote }}
            - name: MAIL_FROM
              value: {{ .Values.env.mailFrom | quote }}
            - name: EMAIL_NOTIFICATION_TIMEOUT
              value: {{ .Values.env.emailNotificationTimeout | quote }}
            - name: METEOR_REACTIVITY_ORDER
              value: {{ .Values.env.meteorReactivityOrder | quote }}
            - name: NODE_OPTIONS
              value: {{ .Values.env.nodeOptions | quote }}
            - name: WRITABLE_PATH
              value: {{ .Values.env.writablePath | quote }}
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adminSecret.name }}
                  key: {{ .Values.adminSecret.usernameKey }}
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adminSecret.name }}
                  key: {{ .Values.adminSecret.emailKey }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adminSecret.name }}
                  key: {{ .Values.adminSecret.passwordKey }}
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            failureThreshold: 180
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 300
            periodSeconds: 20
            failureThreshold: 6
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{ with .Values.extraVolumeMounts }}
          volumeMounts:
{{ toYaml . | indent 12 }}
          {{- end }}
      {{ with .Values.extraVolumes }}
      volumes:
{{ toYaml . | indent 8 }}
      {{- end }}
